export type LandingPage = {
  slug: string; title: string; meta: string; eyebrow: string; headline: string; subheadline: string; cta: string;
  audience: string; problemTitle: string; problemBody: string;
  benefits: { title: string; body: string }[]; examples: { title: string; body: string }[];
  faq: { q: string; a: string }[]; related: string[];
};

export const landingPages: Record<string, LandingPage> = {
  "chatgpt-alternative": {
    slug: "chatgpt-alternative", title: "Flexible ChatGPT Alternative | Clear AI Agents", meta: "Compare a flexible ChatGPT alternative with six AI modes for coding, writing, research, vision, and long-context work—without API keys or setup.", eyebrow: "A more flexible AI workspace", headline: "A flexible ChatGPT alternative for coding, writing, research, and large-context work", subheadline: "Choose from six specialized AI brains in one browser-based workspace — no API keys, model downloads, or tool switching.", cta: "Try Clear AI Agents", audience: "For professionals who use AI across more than one kind of work and want the right mode for each task.", problemTitle: "One model should not have to do every job", problemBody: "A quick rewrite, a repository review, a scanned diagram, and a long research report ask for different strengths. Clear AI Agents lets you switch brains while your work stays in one clean interface.", benefits: [{title:"Six specialized modes",body:"Choose Smart, Fast, Long Context, Creative, Derestricted, or Vision based on the task."},{title:"Less workflow friction",body:"No user-supplied API keys, model files, or separate chat tools to manage."},{title:"More room for real work",body:"Use long-context and vision modes when a short text chat is not enough."}], examples: [{title:"From brief to draft",body:"Plan with Smart, draft with Creative, then polish with Fast."},{title:"From repo to fix",body:"Use Long Context for broader understanding and Fast for focused iterations."},{title:"From screenshot to answer",body:"Use Vision to inspect interfaces, diagrams, and visual documents."}], faq: [{q:"Does this replace ChatGPT?",a:"It can be your primary AI workspace if you value specialized modes, long context, vision, and fewer tool changes. You can also use it alongside other tools."},{q:"Do I need API keys?",a:"No. Model access is managed inside Clear AI Agents."},{q:"Can I switch modes?",a:"Yes. Choose the brain that fits the task from one interface."},{q:"What does the Derestricted mode do?",a:"It aims to reduce unnecessary refusals for legitimate work while retaining safeguards against illegal content."}], related:["ai-for-coding","ai-for-research","long-context-ai"]
  },
  "long-context-ai": {
    slug:"long-context-ai", title:"Long-Context AI for Documents & Code | Clear AI", meta:"Analyze large documents, codebases, books, reports, and research with long-context AI supporting up to 512K in one browser-based workspace.", eyebrow:"Up to 512K context", headline:"Long-context AI for large documents, codebases, books, and research", subheadline:"Work with PDFs, reports, textbooks, case files, repositories, and long notes using context support up to 512K.", cta:"Start a long-context workflow", audience:"For anyone whose source material is too large, connected, or detailed for a short chat window.", problemTitle:"Stop rebuilding context one prompt at a time", problemBody:"Splitting a large source into tiny fragments makes it harder to compare ideas and preserve the full picture. Long Context keeps more relevant material available in the same workflow.", benefits:[{title:"Large source sets",body:"Bring together reports, papers, books, case files, and long notes."},{title:"Codebase understanding",body:"Trace relationships across more files before planning a change."},{title:"Mode switching",body:"Move from Long Context to Smart, Fast, or Vision without changing products."}], examples:[{title:"Compare reports",body:"Extract themes, differences, risks, and unanswered questions across multiple sources."},{title:"Understand a repository",body:"Map modules, dependencies, conventions, and likely impact areas before editing."},{title:"Study a textbook",body:"Build chapter summaries, concept maps, and revision notes from connected material."}], faq:[{q:"What does 512K context mean?",a:"It is the maximum context capacity available on compatible modes. Actual usable context depends on the selected model and content."},{q:"Can it analyze multiple documents?",a:"Yes, where supported by the selected mode and file workflow."},{q:"Can I use it for codebases?",a:"Yes. Long Context is designed for larger repositories and connected technical material."},{q:"Do I need an API key?",a:"No. Clear AI Agents manages model access in the browser-based workspace."}], related:["ai-for-research","ai-for-coding","chatgpt-alternative"]
  },
  "ai-for-coding": {
    slug:"ai-for-coding", title:"AI for Coding, Debugging & Codebases | Clear AI", meta:"Use AI for coding, debugging, code explanation, architecture planning, and codebase understanding with fast, deep, and long-context modes.", eyebrow:"Built for technical workflows", headline:"AI for coding, debugging, planning, and codebase understanding", subheadline:"Use Fast for quick fixes, Smart for architecture and reasoning, and Long Context for larger repositories — all in one workspace.", cta:"Try Clear AI Agents for coding", audience:"For developers, technical founders, analysts, and learners who need more than autocomplete.", problemTitle:"Match the mode to the engineering task", problemBody:"A one-line error and a repository-wide architecture decision do not need the same kind of reasoning. Switch between fast iteration, deeper planning, and larger context as the work changes.", benefits:[{title:"Debug with context",body:"Explain errors, isolate likely causes, and work through fixes step by step."},{title:"Plan before editing",body:"Use Smart for architecture, trade-offs, migration plans, and review checklists."},{title:"Understand more of the repo",body:"Use Long Context for connected files, conventions, and impact analysis."}], examples:[{title:"Bug fixing",body:"Share the error, relevant code, and expected behavior to build a focused fix plan."},{title:"Code explanation",body:"Turn unfamiliar functions or modules into a clear mental model."},{title:"Architecture planning",body:"Compare approaches, surface constraints, and sequence implementation work."}], faq:[{q:"Which languages can I use?",a:"The available models support common programming and scripting languages, though quality varies by model and task."},{q:"Does it run my code?",a:"Treat generated code as a draft to review and test in your own development environment."},{q:"Can it understand a whole repository?",a:"Long Context can hold substantially more connected code, subject to the selected model’s context limit."},{q:"Can I switch between fast and deep modes?",a:"Yes. That is a core part of the workspace."}], related:["long-context-ai","ai-for-research","chatgpt-alternative"]
  },
  "ai-for-research": {
    slug:"ai-for-research", title:"AI for Research & Document Analysis | Clear AI", meta:"Use AI for research, synthesis, paper summaries, argument comparison, and large-document analysis with long-context and vision modes.", eyebrow:"Research without fragmenting the work", headline:"AI for research, synthesis, and document analysis", subheadline:"Summarize papers, compare arguments, extract themes, and turn large source sets into useful working notes.", cta:"Start researching with Clear AI Agents", audience:"For researchers, analysts, students, consultants, and knowledge workers handling complex source material.", problemTitle:"Move from source overload to a usable synthesis", problemBody:"Clear AI Agents helps organize what you provide, compare positions, extract recurring themes, and draft structured notes while keeping the source context close to the work.", benefits:[{title:"Synthesize, not just summarize",body:"Compare claims, methods, assumptions, and disagreements across sources."},{title:"Work across large material",body:"Use Long Context for papers, reports, notes, and document collections."},{title:"Read visual sources",body:"Use Vision for screenshots, charts, diagrams, and scanned pages."}], examples:[{title:"Literature review prep",body:"Create a theme map and identify where sources agree or conflict."},{title:"Report analysis",body:"Extract decisions, evidence, risks, and follow-up questions."},{title:"Working notes",body:"Turn scattered material into structured notes, outlines, and briefing documents."}], faq:[{q:"Will it provide accurate citations?",a:"AI output can be wrong. Verify quotations, citations, numbers, and source claims against the original material before relying on them."},{q:"Can it read scanned pages?",a:"Vision mode can help interpret screenshots and visual documents, subject to image quality."},{q:"Is it suitable for students?",a:"Yes, for study, synthesis, and note-making when used within your institution’s rules."},{q:"How much material can I use?",a:"Compatible modes support context windows up to 512K, with practical limits varying by model and file type."}], related:["long-context-ai","ai-for-writing","chatgpt-alternative"]
  },
  "derestricted-chatgpt-alternative": {
    slug:"derestricted-chatgpt-alternative", title:"Derestricted ChatGPT Alternative | Clear AI Agents", meta:"A derestricted ChatGPT alternative that answers more legitimate work prompts directly—coding, writing, research, and analysis—while keeping safeguards against illegal content.", eyebrow:"Direct answers for real work", headline:"A derestricted ChatGPT alternative that gets on with the job", subheadline:"Tired of unnecessary refusals on legitimate work? Derestricted mode gives you more direct, useful answers for real tasks — with hard-line safeguards against illegal content still in place.", cta:"Try Derestricted mode", audience:"For professionals, developers, writers, and researchers whose legitimate prompts keep hitting overcautious refusals.", problemTitle:"Fewer lectures. More answers.", problemBody:"Mainstream AI chat tools often refuse or over-hedge legitimate requests — security research questions, direct-response copy, complex system configs, or edgy creative fiction. Clear AI Agents' Derestricted mode is tuned to answer legitimate work directly, while still blocking strictly illegal content.", benefits:[{title:"Direct answers",body:"Get a straight answer to legitimate professional prompts instead of a boilerplate refusal."},{title:"Still safe by design",body:"Hard-line safeguards against strictly illegal content remain active at all times."},{title:"One of six brains",body:"Switch to Smart, Fast, Long Context, Creative, or Vision whenever the task changes — same workspace."}], examples:[{title:"Security & sysadmin work",body:"Regex, firewall rules, hardening scripts, and system configuration explained directly."},{title:"Persuasive writing",body:"Direct-response sales copy, punchy scripts, and bold creative fiction without moralizing."},{title:"Blunt analysis",body:"Straightforward critique of arguments, strategies, and documents without excessive hedging."}], faq:[{q:"What does Derestricted mode do?",a:"It reduces unnecessary refusals and hedging on legitimate work prompts, giving more direct and useful answers."},{q:"Is anything blocked?",a:"Yes. Hard-line safeguards against strictly illegal content remain in place at all times."},{q:"Is it a separate app?",a:"No. Derestricted is one of six brains inside the same Clear AI Agents workspace — no API keys or setup."},{q:"Can I switch back to standard modes?",a:"Yes. You can switch between Derestricted, Smart, Fast, Long Context, Creative, and Vision at any time."}], related:["chatgpt-alternative","ai-for-writing","ai-for-coding"]
  },
  "ai-for-writing": {
    slug:"ai-for-writing", title:"AI for Writing, Rewriting & Long-Form Content", meta:"Draft, rewrite, brainstorm, and build long-form content with Creative, Smart, and Fast AI modes in one clean browser-based workspace.", eyebrow:"A flexible writing workspace", headline:"AI for writing, rewriting, drafting, and long-form content", subheadline:"Move from idea to outline, draft, rewrite, and final polish by switching between Creative, Smart, and Fast modes.", cta:"Start writing with Clear AI Agents", audience:"For writers, marketers, creators, founders, and teams building structured long-form work.", problemTitle:"Keep strategy, creativity, and editing in one workflow", problemBody:"Use a reasoning mode to shape the argument, Creative to explore and draft, and Fast to tighten individual sections without moving the brief between separate tools.", benefits:[{title:"Plan the structure",body:"Turn goals, audience, source notes, and constraints into a usable outline."},{title:"Draft with range",body:"Explore angles, scripts, articles, campaigns, and long-form narratives."},{title:"Rewrite with purpose",body:"Improve clarity, tone, flow, compression, and consistency against the same brief."}], examples:[{title:"Blog drafts",body:"Move from search intent and outline to a structured first draft."},{title:"Rewrites",body:"Adapt existing copy for a new audience, tone, channel, or length."},{title:"Brainstorming",body:"Generate directions, compare them, and develop the strongest route."}], faq:[{q:"Can it help with long-form writing?",a:"Yes. Creative and Long Context modes are designed for longer drafts and larger supporting material."},{q:"Can I preserve a specific tone?",a:"Provide examples and clear constraints, then use the same thread to refine consistency."},{q:"Is it useful for rewriting?",a:"Yes. You can ask for changes to clarity, structure, tone, length, or audience fit."},{q:"Do I need API keys?",a:"No. Clear AI Agents manages model access for you."}], related:["ai-for-research","chatgpt-alternative","long-context-ai"]
  }
};

export const landingList = Object.values(landingPages);
