import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, BrainCircuit, Braces, Check, Eye, FileSearch, Gauge, Layers3, Lightbulb, MessageSquareText, PenLine, Search, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { siteConfig, absUrl } from "@/config/site";
import { SiteHeader, SiteFooter } from "@/components/marketing/SiteChrome";
import { ComparisonTable, FaqSection, FinalCTA, LaunchOffer, OfferLine, TrustClarityStrip } from "@/components/marketing/ConversionSections";

const metaTitle = "Clear AI Agents | Six AI Brains for Real Work";
const metaDescription = "One multi-model AI workspace for coding, writing, research, large documents, screenshots, and productivity. No API keys or setup required.";
export const Route = createFileRoute("/")({
  head: () => ({
    meta: [{title:metaTitle},{name:"description",content:metaDescription},{property:"og:title",content:metaTitle},{property:"og:description",content:metaDescription},{property:"og:type",content:"website"},{property:"og:url",content:absUrl("/")},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:title",content:metaTitle},{name:"twitter:description",content:metaDescription}],
    links:[{rel:"canonical",href:absUrl("/")}],
    scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"Clear AI Agents",applicationCategory:"BusinessApplication",operatingSystem:"Web",description:metaDescription,offers:{"@type":"Offer",price:"14.99",priceCurrency:"USD"}})},{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:[...siteConfig.faq,...siteConfig.faqExtra].map(i=>({"@type":"Question",name:i.q,acceptedAnswer:{"@type":"Answer",text:i.a}}))})}],
  }), component: HomePage
});
const icons=[BrainCircuit,Gauge,Layers3,PenLine,MessageSquareText,Eye];
const useCases=[{icon:Braces,title:"Coding & debugging",body:"Explain unfamiliar code, isolate errors, plan architecture, and work across connected files.",to:"/ai-for-coding"},{icon:Search,title:"Research & synthesis",body:"Compare papers, reports, and notes to surface themes, disagreements, and useful next steps.",to:"/ai-for-research"},{icon:FileSearch,title:"Large documents",body:"Work with codebases, textbooks, case files, and reports using context windows up to 512K.",to:"/long-context-ai"},{icon:PenLine,title:"Writing & rewriting",body:"Move from ideas to outlines, long-form drafts, rewrites, and channel-ready copy.",to:"/ai-for-writing"},{icon:Eye,title:"Screenshots & diagrams",body:"Ask questions about interfaces, visual documents, diagrams, and scanned pages."},{icon:Lightbulb,title:"Planning & productivity",body:"Turn scattered thoughts into decisions, checklists, plans, summaries, and finished work."}];
const workflowModes=[
  {name:"Smart",prompt:"Review these research notes and propose a launch plan with clear assumptions.",response:"I’ll structure the source material, surface unresolved assumptions, and create a phased plan. First, here are the four decisions that drive the rest…"},
  {name:"Long Context",prompt:"Compare these reports and identify the strongest recurring findings.",response:"Across the full source set, five themes recur. I’ll map each finding to its supporting documents and flag the two points where the evidence conflicts…"},
  {name:"Vision",prompt:"Review this product screenshot and identify the biggest usability issue.",response:"The primary action competes with two secondary controls. I’ll show how to clarify the hierarchy, improve the labels, and reduce friction in the first interaction…"},
  {name:"Fast",prompt:"Turn these rough notes into a concise project update.",response:"Here’s a polished update: the core build is complete, validation is underway, and the remaining work is focused on launch readiness and final quality checks…"},
] as const;
function HomePage(){const {links,models,pricing,footer}=siteConfig;const [activeMode,setActiveMode]=useState(0);const workflow=workflowModes[activeMode];return <main className="min-h-screen overflow-x-hidden"><SiteHeader/>
<section className="relative min-h-[76vh] border-b border-border/30"><div className="absolute inset-0 -z-10 grid-bg opacity-30"/><div className="mx-auto flex max-w-6xl flex-col items-center px-6 pb-20 pt-20 text-center md:pb-24 md:pt-28"><div className="rounded-full border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary">Six specialized AI modes. No setup.</div><h1 className="mt-7 max-w-5xl text-5xl font-black leading-[1.03] md:text-7xl">Six AI brains. <span className="text-gradient">One workspace for real work.</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-foreground md:text-xl">Choose the right AI for coding, writing, research, large documents, screenshots, and everyday productivity — without API keys, model files, or setup headaches.</p><div className="mt-9 flex w-full flex-col justify-center gap-3 sm:w-auto sm:flex-row"><Button asChild size="lg" className="rounded-full shadow-neon"><a href={links.signup} data-ph-event="cta_clicked">Start free <ArrowRight/></a></Button><Button asChild size="lg" variant="outline" className="rounded-full"><a href="#brains">See the six brains</a></Button></div><div className="mt-6"><OfferLine/></div></div></section>
<TrustClarityStrip/>
<section id="brains" className="py-20 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase text-primary">The six brains</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">Stop forcing one model to do every job.</h2><p className="mt-5 text-lg text-muted-foreground">Switch modes as your work changes. The interface stays familiar; the strengths behind it do not.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{models.map((m,i)=>{const Icon=icons[i];return <article key={m.key} className="group rounded-lg border border-border/40 bg-card/30 p-6 hover:border-primary/50"><div className="flex items-start justify-between"><Icon className="h-6 w-6 text-primary"/><span className="rounded-full bg-secondary px-2.5 py-1 text-[10px] font-semibold text-muted-foreground">{m.badge}</span></div><h3 className="mt-6 text-xl font-bold">{m.name}</h3><p className="mt-2 min-h-16 text-sm leading-relaxed text-muted-foreground">{m.blurb}</p><p className="mt-5 border-t border-border/30 pt-4 text-[11px] text-muted-foreground/70">{m.engine}</p></article>})}</div></div></section>
<section id="use-cases" className="border-y border-border/40 bg-card/15 py-20 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase text-accent">Built around your work</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">One place for the work that usually spills across tools.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{useCases.map(u=>{const Icon=u.icon;const content=<><Icon className="h-5 w-5 text-primary"/><h3 className="mt-5 text-lg font-semibold">{u.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{u.body}</p>{u.to&&<span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-primary">Explore workflow <ArrowRight className="h-3 w-3"/></span>}</>;return u.to?<Link key={u.title} to={u.to as "/ai-for-coding"} className="rounded-lg border border-border/40 bg-background/40 p-6 hover:border-primary/50">{content}</Link>:<article key={u.title} className="rounded-lg border border-border/40 bg-background/40 p-6">{content}</article>})}</div></div></section>
<section className="py-20 md:py-28"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase text-primary">A native multi-model workflow</p><h2 className="mt-3 text-4xl font-bold">The task changes. Your workspace does not.</h2><p className="mt-5 leading-relaxed text-muted-foreground">Start with deeper reasoning, bring in large source material, inspect a screenshot, then switch to a faster mode for the final polish.</p><Button asChild variant="outline" className="mt-7 rounded-full"><Link to="/chatgpt-alternative">Compare the workspace <ArrowRight/></Link></Button></div><div className="rounded-lg border border-border/40 bg-card/30 p-5"><div className="flex flex-wrap gap-2 border-b border-border/30 pb-4" role="tablist" aria-label="AI brain demo">{workflowModes.map((mode,i)=><Button key={mode.name} type="button" size="sm" variant={i===activeMode?"default":"secondary"} className="h-7 rounded-full px-3 text-xs" role="tab" aria-selected={i===activeMode} onClick={()=>setActiveMode(i)}>{mode.name}</Button>)}</div><div className="space-y-4 py-5" role="tabpanel" aria-live="polite"><div className="ml-auto max-w-[82%] rounded-lg bg-secondary p-4 text-sm">{workflow.prompt}</div><div className="max-w-[90%] rounded-lg border border-primary/30 bg-primary/5 p-4 text-sm leading-relaxed"><Sparkles className="mr-2 inline h-4 w-4 text-primary"/>{workflow.response}</div></div><div className="border-t border-border/30 pt-4 text-xs text-muted-foreground"><WandSparkles className="mr-2 inline h-4 w-4 text-accent"/>Switch brains without rebuilding your workflow.</div></div></div></section>
<section id="comparison" className="border-y border-border/40 bg-card/15 py-20 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="mb-10 max-w-3xl"><p className="text-xs font-semibold uppercase text-accent">Compare your options</p><h2 className="mt-3 text-4xl font-bold">More range than a one-model chat. Less friction than DIY APIs.</h2></div><ComparisonTable/></div></section>
<section id="pricing" className="py-20 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase text-primary">Simple pricing</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">Start free. Upgrade when the work gets serious.</h2><p className="mt-4 text-muted-foreground">No API bills to calculate and no model infrastructure to manage.</p></div><div className="mx-auto mt-10 max-w-3xl"><LaunchOffer/></div><div className="mt-8 grid gap-5 lg:grid-cols-3">{Object.entries(pricing).map(([key,p])=><article key={key} className={`flex flex-col rounded-lg border p-6 ${key==="pro"?"border-primary/60 bg-primary/5 shadow-neon":"border-border/40 bg-card/30"}`}><div className="flex items-center justify-between"><h3 className="text-xl font-bold">{p.name}</h3>{key==="pro"&&<span className="text-xs font-semibold text-primary">Most popular</span>}</div><p className="mt-5"><span className="text-4xl font-black">{p.price}</span><span className="text-sm text-muted-foreground">{p.period}</span></p><p className="mt-3 min-h-12 text-sm text-muted-foreground">{p.blurb}</p><ul className="my-6 space-y-3">{p.features.map(f=><li key={f} className="flex gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{f}</li>)}</ul><Button asChild variant={key==="pro"?"default":"outline"} className="mt-auto rounded-full"><a href={key==="free"?links.signup:key==="pro"?links.proCheckout:links.powerCheckout} target={key==="free"?undefined:"_blank"} rel={key==="free"?undefined:"noopener noreferrer"} data-ph-event="cta_clicked">{p.cta}<ArrowRight/></a></Button></article>)}</div></div></section>
<FaqSection items={[...siteConfig.faq,...siteConfig.faqExtra]}/>
<section id="community" className="border-y border-border/40 bg-card/15 py-16"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-6 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase text-accent">Community</p><h2 className="mt-2 text-2xl font-bold">Build with other practical AI users.</h2><p className="mt-2 text-sm text-muted-foreground">Join product updates and useful workflow conversations.</p></div><div className="flex flex-wrap gap-3"><Button asChild variant="outline" className="rounded-full"><a href={links.whatsapp} target="_blank" rel="noopener noreferrer">Join WhatsApp</a></Button><Button asChild variant="outline" className="rounded-full"><a href={links.linkedin} target="_blank" rel="noopener noreferrer">Follow on LinkedIn</a></Button></div></div></section>
<section id="contact" className="py-20"><div className="mx-auto grid max-w-5xl gap-10 px-6 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-primary">Contact</p><h2 className="mt-3 text-3xl font-bold">Have a question before you start?</h2><p className="mt-4 text-muted-foreground">Tell us what you want to use Clear AI Agents for. We’ll help you choose the right plan.</p></div><form className="grid gap-4" onSubmit={(e)=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get("name")||"").slice(0,100);const email=String(data.get("email")||"").slice(0,255);const body=String(data.get("body")||"").slice(0,1000);window.location.href=`mailto:support@clearaiagents.com?subject=${encodeURIComponent(`Clear AI Agents inquiry from ${name}`)}&body=${encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${body}`)}`;}}><label className="text-sm">Name<input name="name" autoComplete="name" maxLength={100} required className="mt-2 w-full rounded-md border border-border/60 bg-card/40 px-4 py-3 outline-none focus:border-primary"/></label><label className="text-sm">Email<input type="email" name="email" autoComplete="email" maxLength={255} required className="mt-2 w-full rounded-md border border-border/60 bg-card/40 px-4 py-3 outline-none focus:border-primary"/></label><label className="text-sm">Message<textarea name="body" maxLength={1000} required rows={4} className="mt-2 w-full rounded-md border border-border/60 bg-card/40 px-4 py-3 outline-none focus:border-primary"/></label><Button type="submit" className="rounded-full">Contact us <ArrowRight/></Button></form></div></section>
<FinalCTA/><SiteFooter/></main>}
