import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/config/site";
import { landingPages } from "@/lib/landing-pages";

export function OfferLine({ centered=true }: { centered?: boolean }) { const p=siteConfig.promo; return <p className={`text-xs leading-relaxed text-muted-foreground ${centered?"text-center":""}`}>Use <strong className="text-foreground">{p.discountCode}</strong> for {p.discountPercent}% off your first month</p> }
export function TrustClarityStrip(){return <section aria-label="Product facts" className="border-y border-border/40 bg-card/20"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-px px-6 py-5 text-xs text-muted-foreground sm:grid-cols-3 lg:grid-cols-5">{["Browser-based","No setup required","Multi-model workspace","Up to 512K + vision","Cancel anytime"].map((x)=><div key={x} className="flex items-center justify-center gap-2 py-2"><Check className="h-3.5 w-3.5 text-primary"/><span>{x}</span></div>)}</div></section>}
export function LaunchOffer(){const p=siteConfig.promo;return <div className="neon-border rounded-lg bg-card/40 p-5 text-left"><p className="text-xs font-semibold uppercase text-accent">Founder launch offer</p><div className="mt-3"><p className="text-sm"><code className="font-bold text-accent">{p.discountCode}</code><span className="mt-1 block text-muted-foreground">{p.discountPercent}% off your first month</span></p></div></div>}
export function FaqSection({items}:{items:{q:string;a:string}[]}){return <section id="faq" className="py-20 md:py-28"><div className="mx-auto max-w-3xl px-6"><div className="mb-10 text-center"><p className="text-xs font-semibold uppercase text-primary">FAQ</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">Clear answers before you start.</h2></div><div className="space-y-3">{items.map(i=><details key={i.q} className="group rounded-lg border border-border/40 bg-card/30 p-5 open:border-primary/40"><summary className="cursor-pointer list-none font-semibold">{i.q}<span className="float-right text-primary">+</span></summary><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{i.a}</p></details>)}</div></div></section>}
export function FinalCTA({title="Bring your real work. Pick the right brain. Start in under a minute.", cta="Start free"}:{title?:string;cta?:string}){return <section className="py-20"><div className="mx-auto max-w-5xl px-6"><div className="neon-border rounded-lg bg-card/40 p-8 text-center md:p-12"><Sparkles className="mx-auto h-6 w-6 text-primary"/><h2 className="mx-auto mt-4 max-w-3xl text-3xl font-bold md:text-4xl">{title}</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">One workspace for drafts, code, research, documents, screenshots, and the everyday tasks between them.</p><Button asChild size="lg" className="mt-7 rounded-full shadow-neon"><a href={siteConfig.links.signup} data-ph-event="cta_clicked">{cta}<ArrowRight/></a></Button><div className="mt-5"><OfferLine/></div></div></div></section>}
export function RelatedPages({slugs}:{slugs:string[]}){return <section className="pb-20"><div className="mx-auto max-w-6xl px-6"><h2 className="mb-5 text-2xl font-bold">Related workflows</h2><div className="grid gap-4 md:grid-cols-3">{slugs.map(slug=>{const p=landingPages[slug];if(!p)return null;return <Link key={slug} to={`/${slug}` as "/ai-for-coding"} className="rounded-lg border border-border/40 bg-card/30 p-5 hover:border-primary/50"><h3 className="font-semibold">{p.eyebrow}</h3><p className="mt-2 text-sm text-muted-foreground">{p.headline}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary">Explore <ArrowRight className="h-3 w-3"/></span></Link>})}</div></div></section>}
export const comparisonRows=[{feature:"Multiple specialized AI modes",clear:"Six included",single:"Usually one default",diy:"You configure each"},{feature:"Long-context support",clear:"Up to 512K",single:"Varies",diy:"Varies by provider"},{feature:"Vision support",clear:"Included",single:"Varies",diy:"Setup required"},{feature:"No API keys needed",clear:"Included",single:"Included",diy:"No"},{feature:"Direct-answer option",clear:"Included",single:"Varies",diy:"Model dependent"},{feature:"One clean workspace",clear:"Included",single:"Included",diy:"You build it"}];
export function ComparisonTable(){return <div className="overflow-x-auto rounded-lg border border-border/40 bg-card/30"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-border/40 text-xs text-muted-foreground"><th className="p-4">Capability</th><th className="p-4 text-primary">Clear AI Agents</th><th className="p-4">One-model chat</th><th className="p-4">DIY API workflow</th></tr></thead><tbody>{comparisonRows.map(r=><tr key={r.feature} className="border-b border-border/20 last:border-0"><th className="p-4 font-medium">{r.feature}</th><td className="p-4 text-primary"><Check className="mr-1.5 inline h-4 w-4"/>{r.clear}</td><td className="p-4 text-muted-foreground">{r.single}</td><td className="p-4 text-muted-foreground">{r.diy}</td></tr>)}</tbody></table></div>}
