import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, FileText, Layers3, Sparkles } from "lucide-react";
import type { LandingPage } from "@/lib/landing-pages";
import { siteConfig } from "@/config/site";
import { Button } from "@/components/ui/button";
import { SiteHeader, SiteFooter } from "./SiteChrome";
import { FaqSection, FinalCTA, LaunchOffer, RelatedPages, TrustClarityStrip } from "./ConversionSections";

export function LandingPageTemplate({ page }: { page: LandingPage }) {
  return <main className="min-h-screen overflow-x-hidden"><SiteHeader/>
    <section className="relative border-b border-border/30"><div className="absolute inset-0 -z-10 grid-bg opacity-25"/><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase text-primary">{page.eyebrow}</p><h1 className="mt-5 text-4xl font-black leading-tight md:text-6xl">{page.headline}</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-muted-foreground md:text-xl">{page.subheadline}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="rounded-full shadow-neon"><a href={siteConfig.links.signup} data-ph-event="cta_clicked">{page.cta}<ArrowRight/></a></Button><Button asChild size="lg" variant="outline" className="rounded-full"><Link to="/" hash="brains">See the 6 brains</Link></Button></div><p className="mt-5 text-xs text-muted-foreground">Start free · No API keys · Browser-based</p></div></div></section>
    <TrustClarityStrip/>
    <section className="py-20 md:py-28"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase text-accent">Who it is for</p><h2 className="mt-3 text-3xl font-bold">{page.problemTitle}</h2><p className="mt-4 leading-relaxed text-muted-foreground">{page.audience}</p><p className="mt-4 leading-relaxed text-muted-foreground">{page.problemBody}</p></div><div className="grid gap-4 sm:grid-cols-3">{page.benefits.map((b,i)=><article key={b.title} className="rounded-lg border border-border/40 bg-card/30 p-5"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 text-sm font-bold text-primary">0{i+1}</span><h3 className="mt-5 font-semibold">{b.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{b.body}</p></article>)}</div></div></section>
    <section className="border-y border-border/40 bg-card/15 py-20"><div className="mx-auto max-w-6xl px-6"><p className="text-xs font-semibold uppercase text-primary">Practical examples</p><h2 className="mt-3 text-3xl font-bold">How this fits into real work</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{page.examples.map((e,i)=><article key={e.title} className="rounded-lg border border-border/40 bg-background/50 p-6">{i===0?<FileText className="h-5 w-5 text-primary"/>:i===1?<Layers3 className="h-5 w-5 text-accent"/>:<Sparkles className="h-5 w-5 text-primary"/>}<h3 className="mt-4 text-lg font-semibold">{e.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{e.body}</p></article>)}</div></div></section>
    <section className="py-20"><div className="mx-auto max-w-5xl px-6"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-accent">Clear by design</p><h2 className="mt-3 text-3xl font-bold">Choose a brain. Keep the workspace.</h2><ul className="mt-6 space-y-4">{["No user-supplied API keys or model downloads","Switch modes as the task changes","Long-context and vision available in the same interface","Use the direct-answer option when standard modes become overly cautious"].map(x=><li key={x} className="flex gap-3 text-sm text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul></div><LaunchOffer showFree={false}/></div></div></section>
    <FaqSection items={page.faq}/><RelatedPages slugs={page.related}/><FinalCTA title={page.headline} cta={page.cta} showFree={false}/><SiteFooter/>
  </main>;
}
