/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LongContextAiRouteImport } from './routes/long-context-ai'
import { Route as DerestrictedChatgptAlternativeRouteImport } from './routes/derestricted-chatgpt-alternative'
import { Route as DataPolicyRouteImport } from './routes/data-policy'
import { Route as ChatgptAlternativeRouteImport } from './routes/chatgpt-alternative'
import { Route as AiForWritingRouteImport } from './routes/ai-for-writing'
import { Route as AiForResearchRouteImport } from './routes/ai-for-research'
import { Route as AiForCodingRouteImport } from './routes/ai-for-coding'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LongContextAiRoute = LongContextAiRouteImport.update({
  id: '/long-context-ai',
  path: '/long-context-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DerestrictedChatgptAlternativeRoute =
  DerestrictedChatgptAlternativeRouteImport.update({
    id: '/derestricted-chatgpt-alternative',
    path: '/derestricted-chatgpt-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataPolicyRoute = DataPolicyRouteImport.update({
  id: '/data-policy',
  path: '/data-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptAlternativeRoute = ChatgptAlternativeRouteImport.update({
  id: '/chatgpt-alternative',
  path: '/chatgpt-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const AiForWritingRoute = AiForWritingRouteImport.update({
  id: '/ai-for-writing',
  path: '/ai-for-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiForResearchRoute = AiForResearchRouteImport.update({
  id: '/ai-for-research',
  path: '/ai-for-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AiForCodingRoute = AiForCodingRouteImport.update({
  id: '/ai-for-coding',
  path: '/ai-for-coding',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-for-coding': typeof AiForCodingRoute
  '/ai-for-research': typeof AiForResearchRoute
  '/ai-for-writing': typeof AiForWritingRoute
  '/chatgpt-alternative': typeof ChatgptAlternativeRoute
  '/data-policy': typeof DataPolicyRoute
  '/derestricted-chatgpt-alternative': typeof DerestrictedChatgptAlternativeRoute
  '/long-context-ai': typeof LongContextAiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-for-coding': typeof AiForCodingRoute
  '/ai-for-research': typeof AiForResearchRoute
  '/ai-for-writing': typeof AiForWritingRoute
  '/chatgpt-alternative': typeof ChatgptAlternativeRoute
  '/data-policy': typeof DataPolicyRoute
  '/derestricted-chatgpt-alternative': typeof DerestrictedChatgptAlternativeRoute
  '/long-context-ai': typeof LongContextAiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-for-coding': typeof AiForCodingRoute
  '/ai-for-research': typeof AiForResearchRoute
  '/ai-for-writing': typeof AiForWritingRoute
  '/chatgpt-alternative': typeof ChatgptAlternativeRoute
  '/data-policy': typeof DataPolicyRoute
  '/derestricted-chatgpt-alternative': typeof DerestrictedChatgptAlternativeRoute
  '/long-context-ai': typeof LongContextAiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/ai-for-coding'
    | '/ai-for-research'
    | '/ai-for-writing'
    | '/chatgpt-alternative'
    | '/data-policy'
    | '/derestricted-chatgpt-alternative'
    | '/long-context-ai'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/ai-for-coding'
    | '/ai-for-research'
    | '/ai-for-writing'
    | '/chatgpt-alternative'
    | '/data-policy'
    | '/derestricted-chatgpt-alternative'
    | '/long-context-ai'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/ai-for-coding'
    | '/ai-for-research'
    | '/ai-for-writing'
    | '/chatgpt-alternative'
    | '/data-policy'
    | '/derestricted-chatgpt-alternative'
    | '/long-context-ai'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AiForCodingRoute: typeof AiForCodingRoute
  AiForResearchRoute: typeof AiForResearchRoute
  AiForWritingRoute: typeof AiForWritingRoute
  ChatgptAlternativeRoute: typeof ChatgptAlternativeRoute
  DataPolicyRoute: typeof DataPolicyRoute
  DerestrictedChatgptAlternativeRoute: typeof DerestrictedChatgptAlternativeRoute
  LongContextAiRoute: typeof LongContextAiRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-context-ai': {
      id: '/long-context-ai'
      path: '/long-context-ai'
      fullPath: '/long-context-ai'
      preLoaderRoute: typeof LongContextAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derestricted-chatgpt-alternative': {
      id: '/derestricted-chatgpt-alternative'
      path: '/derestricted-chatgpt-alternative'
      fullPath: '/derestricted-chatgpt-alternative'
      preLoaderRoute: typeof DerestrictedChatgptAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-policy': {
      id: '/data-policy'
      path: '/data-policy'
      fullPath: '/data-policy'
      preLoaderRoute: typeof DataPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-alternative': {
      id: '/chatgpt-alternative'
      path: '/chatgpt-alternative'
      fullPath: '/chatgpt-alternative'
      preLoaderRoute: typeof ChatgptAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-for-writing': {
      id: '/ai-for-writing'
      path: '/ai-for-writing'
      fullPath: '/ai-for-writing'
      preLoaderRoute: typeof AiForWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-for-research': {
      id: '/ai-for-research'
      path: '/ai-for-research'
      fullPath: '/ai-for-research'
      preLoaderRoute: typeof AiForResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-for-coding': {
      id: '/ai-for-coding'
      path: '/ai-for-coding'
      fullPath: '/ai-for-coding'
      preLoaderRoute: typeof AiForCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AiForCodingRoute: AiForCodingRoute,
  AiForResearchRoute: AiForResearchRoute,
  AiForWritingRoute: AiForWritingRoute,
  ChatgptAlternativeRoute: ChatgptAlternativeRoute,
  DataPolicyRoute: DataPolicyRoute,
  DerestrictedChatgptAlternativeRoute: DerestrictedChatgptAlternativeRoute,
  LongContextAiRoute: LongContextAiRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
